---
stages:
  - syntax
  - unit
  - smoke

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# Set `rubygems_version` in the .sync.yml to set a value"
  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.5.7-Puppet ~> 6:
  stage: syntax
  image: ruby:2.5.7
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 6'

parallel_spec-Ruby 2.5.7-Puppet ~> 6:
  stage: unit
  image: ruby:2.5.7
  script:
    - gem --version
    - bundle -v
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 6'

parallel_spec-Ruby 2.4.5-Puppet ~> 5:
  stage: unit
  image: ruby:2.4.5
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5'

smoke syslog-ng puppet 5:
  stage: smoke
  image: ruby:2.5.3
  variables:
    PUPPET_GEM_VERSION: "~> 5"
  script:
  - apt-get update
  - apt-get install syslog-ng -y
  - syslog-ng --version
  - bundle install --without system_tests --path vendor/bundle
  - bundle exec puppet --version
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz
  - bundle exec ./smoke/test
smoke syslog-ng latest:
  stage: smoke
  allow_failure: true
  image:
    name: balabit/syslog-ng:latest
    entrypoint:
    - ''
  before_script: []
  script:
  - apt-get update
  - apt-get install ruby bundler -y
  - bundle install --without system_tests --path vendor/bundle
  - bundle exec puppet --version
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz
  - bundle exec ./smoke/test

